apiVersion: v1
kind: Service
metadata:
  name: zenodo-postgres
  labels: 
    app: zenodo
spec:
  ports:
    - port: 5432
  selector:
    app: zenodo
    tier: postgres
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zenodo-postgres
  labels:
    app: zenodo
spec:
  selector:
    matchLabels:
      app: zenodo
      tier: postgres
  serviceName: zenodo-postgre
  template:
    metadata:
      labels:
        app: zenodo
        tier: postgres
    spec:
      volumes:
        - name: db-pv-storage
          persistentVolumeClaim:
            claimName: zenodo-postgres-pv-claim
      containers:
      - name: postgres
        image: postgres:11
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: zenodo-secrets
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: zenodo-secrets
                key: password
        volumeMounts:
        - name: db-pv-storage
          mountPath: /var/lib/postgresql/data
